version: '2.0'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mariadb_cf
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=testdb
    ports:
     - 3307:3306
    volumes:
     - ./database:/var/lib/mysql
     - ./_conf/mariadb.cnf:/etc/mysql/my.cnf:ro
